### ISSUE TITLE
Look into Atlantis

### ISSUE THREAD

**Issue by cthulhuplus** [CMSgov/eAPD#3127]
QA/Review tool for Terraform, puts terraform plan into pull request for reviews, integrates with GitHub

### This task is done when...
 - [ ] Determine if Atlantis is a good fit for eAPD

**Comment by cthulhuplus** [comment]
https://www.runatlantis.io/

**Comment by cthulhuplus** [comment]
Can't currently implement Atlantis because another group at CMS is using it. 
https://www.runatlantis.io/docs/access-credentials.html#generating-an-access-token
![image.png](https://images.zenhubusercontent.com/5e9749aa5773ead7746338c1/4821599f-b456-4532-a3f5-70dff832dfbf)

**Comment by cthulhuplus** [comment]
https://www.runatlantis.io/guide/testing-locally.html#install-terraform

**Comment by cthulhuplus** [comment]
Require PR be approved before apply
```
# repos.yaml
repos:
- id: /.*/
  apply_requirements: [approved]
```

**Comment by cthulhuplus** [comment]
Setting up local Terraform test
https://www.runatlantis.io/guide/testing-locally.html#create-a-pull-request

Notes on installation
```
ngrok http 4141
```
Update GitHub Webhook and atlantis.yml URL value to the value provided by ngrok http 4141

My atlantis start script:
```
atlantis server --atlantis-url="$URL" --gh-user="$USERNAME" --gh-token="$TOKEN" --gh-webhook-secret="$SECRET" --config ~/atlantis.yml
```

My atlantis.yml
```
version: 3
allow-draft-prs: true
repo-allowlist: "github.com/CMSgov/eAPD"
repos: "github.com/CMSgov/eAPD"
var-file-allowlist: "/mnt/c/Users/brook/Git/hashi_files/terraform"
enable-diff-markdown-format: true
default-tf-version: "v1.2.4"
projects:
- name: public
  dir: terraform/legacy/public
  terraform_version: v1.2.4
  workflow: public
  apply_requirements: [mergeable]
workflows:
  public:
    plan:
      steps:
      - init
      - plan:
        extra_args: ["-var-file", "public.tfvars"]
```
